apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-build
spec:
  resources:
    - name: pipeline-git
      type: git
  tasks:
    - name: mvn
      taskRef:
        name: maven-task
      resources:
        inputs:
          - name: source
            resource: pipeline-git
      

