apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: maven-proj
spec:
  resources: 
    - name: pipeline-git
      resourceSpec: 
        type: git
        params:
          - name: revision
            value: master
          - name: url
            value: https://github.com/jenkins-docs/simple-java-maven-app.git
  pipelineSpec:
    resources:
      - name: pipeline-git
        type: git
    tasks:
      - name: build
        resources:
          inputs:
            - name: source
              resource: pipeline-git
        taskSpec:
          resources:
            inputs:
              - name: source
                type: git
          steps:
            - name: build-step
              image: maven:3-alpine
              workingDir: $(resources.inputs.source.path)
              command:
                - mvn
                - -B
                - -DskipTests
                - clean
                - package

